services:
  devendevour.iankulin.com:
    build: .
    image: ghcr.io/iankulin/devendevour.iankulin.com:latest
    container_name: devendevour.iankulin.com
    ports:
      - "8080:80"
    restart: unless-stopped
